// playground/vue/src/App.vue
<script setup lang="ts">
import Demo from '@nova-design/components/button/demo/vue/index.vue'
</script>

<template>
  <Demo />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// playground/react/src/App.tsx
import React from 'react'
import './App.css'

// import Demo from '@nova-design/components/button/demo/react/index'

// import Demo from '@nova-design/components/button/demo/react/index.tsx'
// import '@nova-design/core/lib/button'

function App() {
  return (
    <>
      <nova-button ></nova-button>
      {/* <Demo></Demo> */}
    </>
  )
}

export default App
